// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeServe.Data;

#nullable disable

namespace WeServe.Migrations
{
    [DbContext(typeof(WeServeContext))]
    [Migration("20230802172108_AddApprovalToOrganizationTable")]
    partial class AddApprovalToOrganizationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WeServe.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Event", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5053),
                            CreatedByUserId = 3,
                            Description = "Join us for a fun-filled summer festival!",
                            Details = "This event has no details.",
                            EndDate = new DateTime(2023, 8, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://placehold.co/320x320",
                            IsDeleted = false,
                            Location = "Central Park, New York",
                            Name = "Summer Festival",
                            OrganizationId = 1,
                            StartDate = new DateTime(2023, 8, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5054)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5062),
                            CreatedByUserId = 3,
                            Description = "Learn about the latest tech trends and innovations.",
                            Details = "This event has no details.",
                            EndDate = new DateTime(2023, 9, 22, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://placehold.co/320x320",
                            IsDeleted = false,
                            Location = "Tech Convention Center, San Francisco",
                            Name = "Tech Conference",
                            OrganizationId = 1,
                            StartDate = new DateTime(2023, 9, 20, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5062)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5064),
                            CreatedByUserId = 3,
                            Description = "Admire stunning artworks from talented artists.",
                            Details = "This event has no details.",
                            EndDate = new DateTime(2023, 10, 20, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://placehold.co/320x320",
                            IsDeleted = false,
                            Location = "City Art Gallery, London",
                            Name = "Art Exhibition",
                            OrganizationId = 1,
                            StartDate = new DateTime(2023, 10, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5065)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5066),
                            CreatedByUserId = 3,
                            Description = "Run for a cause and support local charities.",
                            Details = "This event has no details.",
                            EndDate = new DateTime(2023, 11, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://placehold.co/320x320",
                            IsDeleted = false,
                            Location = "Riverside Park, Chicago",
                            Name = "Charity Run",
                            OrganizationId = 1,
                            StartDate = new DateTime(2023, 11, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5067)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5069),
                            CreatedByUserId = 3,
                            Description = "Get into the holiday spirit with festive vendors.",
                            Details = "This event has no details.",
                            EndDate = new DateTime(2023, 12, 24, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "https://placehold.co/320x320",
                            IsDeleted = false,
                            Location = "Town Square, Paris",
                            Name = "Holiday Market",
                            OrganizationId = 1,
                            StartDate = new DateTime(2023, 12, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5069)
                        });
                });

            modelBuilder.Entity("WeServe.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Organizations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "123 Main St.",
                            Banner = "https://placehold.co/640x320",
                            City = "City",
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5026),
                            Description = "This is the first organization.",
                            Email = "email@me.com",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Organization 1",
                            PhoneNumber = "1234567890",
                            ProfilePicture = "https://placehold.co/320x320",
                            State = "State",
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5027),
                            Website = "https://www.google.com",
                            ZipCode = "12345"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "123 Main St.",
                            Banner = "https://placehold.co/640x320",
                            City = "City",
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5033),
                            Description = "This is the second organization.",
                            Email = "email@me.com",
                            IsApproved = false,
                            IsDeleted = false,
                            Name = "Organization 2",
                            PhoneNumber = "1234567890",
                            ProfilePicture = "https://placehold.co/320x320",
                            State = "State",
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(5034),
                            Website = "https://www.google.com",
                            ZipCode = "12345"
                        });
                });

            modelBuilder.Entity("WeServe.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Major")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Age = 0,
                            Bio = "This user has not set a bio yet.",
                            ConcurrencyStamp = "8ba170b7-6215-489e-9419-7b461ef0efc9",
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4679),
                            Email = "justin@jkruskie.com",
                            EmailConfirmed = false,
                            FirstName = "Justin",
                            IsBanned = false,
                            IsDeleted = false,
                            LastName = "Kruskie",
                            LockoutEnabled = false,
                            Major = "Undeclared",
                            NormalizedEmail = "JUSTIN@JKRUSKIE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEClaPu/Uv3V4DO4shUhMj7nFQfI8sFHMZgzjX3YaDYoELc3adYt3x5MPWmzttr37hg==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://placehold.co/320x320",
                            Role = "admin",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4728),
                            Year = "Freshman"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Age = 0,
                            Bio = "This user has not set a bio yet.",
                            ConcurrencyStamp = "588521a9-0436-4552-924a-d2e60e31b6aa",
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4758),
                            Email = "student@weserve.com",
                            EmailConfirmed = false,
                            FirstName = "Student",
                            IsBanned = false,
                            IsDeleted = false,
                            LastName = "Account",
                            LockoutEnabled = false,
                            Major = "Undeclared",
                            NormalizedEmail = "STUDENT@WESERVE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEClaPu/Uv3V4DO4shUhMj7nFQfI8sFHMZgzjX3YaDYoELc3adYt3x5MPWmzttr37hg==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://placehold.co/320x320",
                            Role = "student",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4762),
                            Year = "Freshman"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Age = 0,
                            Bio = "This user has not set a bio yet.",
                            ConcurrencyStamp = "2db7c719-30ab-45e9-9899-286db3500921",
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4805),
                            Email = "organization@weserve.com",
                            EmailConfirmed = false,
                            FirstName = "Organization",
                            IsBanned = false,
                            IsDeleted = false,
                            LastName = "Account",
                            LockoutEnabled = false,
                            Major = "Undeclared",
                            NormalizedEmail = "ORGANIZATION@WESERVE.COM",
                            OrganizationId = 1,
                            PasswordHash = "AQAAAAIAAYagAAAAEClaPu/Uv3V4DO4shUhMj7nFQfI8sFHMZgzjX3YaDYoELc3adYt3x5MPWmzttr37hg==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://placehold.co/320x320",
                            Role = "organization",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4806),
                            Year = "Freshman"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Age = 0,
                            Bio = "This user has not set a bio yet.",
                            ConcurrencyStamp = "a567046a-f084-441c-aa42-de0a41bd5f76",
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4810),
                            Email = "moderator@weserve.com",
                            EmailConfirmed = false,
                            FirstName = "Moderator",
                            IsBanned = false,
                            IsDeleted = false,
                            LastName = "Account",
                            LockoutEnabled = false,
                            Major = "Undeclared",
                            NormalizedEmail = "MODERATOR@WESERVE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEClaPu/Uv3V4DO4shUhMj7nFQfI8sFHMZgzjX3YaDYoELc3adYt3x5MPWmzttr37hg==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://placehold.co/320x320",
                            Role = "moderator",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4810),
                            Year = "Freshman"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Age = 0,
                            Bio = "This user has not set a bio yet.",
                            ConcurrencyStamp = "0f34371b-4e9c-4cd4-a74b-14dac9846846",
                            CreatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4820),
                            Email = "admin@weserve.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            IsBanned = false,
                            IsDeleted = false,
                            LastName = "Account",
                            LockoutEnabled = false,
                            Major = "Undeclared",
                            NormalizedEmail = "ADMIN@WESERVE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEClaPu/Uv3V4DO4shUhMj7nFQfI8sFHMZgzjX3YaDYoELc3adYt3x5MPWmzttr37hg==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "https://placehold.co/320x320",
                            Role = "admin",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2023, 8, 2, 13, 21, 8, 520, DateTimeKind.Local).AddTicks(4821),
                            Year = "Freshman"
                        });
                });

            modelBuilder.Entity("WeServe.Models.Event", b =>
                {
                    b.HasOne("WeServe.Models.User", "CreatedByUser")
                        .WithMany("Events")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeServe.Models.Organization", "Organization")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("WeServe.Models.User", b =>
                {
                    b.HasOne("WeServe.Models.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("WeServe.Models.Organization", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WeServe.Models.User", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
